POST http://localhost:3001/orders
Content-Type: application/json

{
  "status": "delivered",
  "buyer": {
    "name": "Julia Martina Perez Perez de la Nueva Bar Bar Bar bar bar Julia Martina P",
    "phone": 573186399528,
    "state": "Pasco",
    "city": "Pasco",
    "street": "Carrera 2 sur #23-4, Barrio La Lora"
  },
  "cart": [
    {
      "product": "62785d15fa0cfa56a8d55586",
      "qty": 2,
      "variant": 0
    }
  ],
  "totalPrice": 59900
}
###
POST https://mobile.servientrega.com/Services/ShipmentTracking/api/ControlRastreovalidaciones HTTP/1.1
Content-Type: application/json

{
  "numeroGuia": "2150614102",
  "idValidacionUsuario": "0",
  "tipoDatoValidar": "0",
  "datoRespuestaUsuario": "0",
  "idpais": 1,
  "lenguaje": "es"
}